FROM rust:1.85-slim-bullseye AS builder
RUN apt-get update && \
    apt-get install -y --no-install-recommends git pkg-config libssl-dev && \
    rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/c3rb3ru5d3d53c/binlex.git /src
WORKDIR /src
RUN cargo install --path .

FROM debian:bullseye-slim
COPY --from=builder /usr/local/cargo/bin/binlex /usr/local/bin/binlex
# Keep container running infinitely
CMD ["tail", "-f", "/dev/null"]
