FROM rust:1.85-slim-bullseye AS builder
RUN apt-get update && \
    apt-get install -y --no-install-recommends git pkg-config libssl-dev && \
    rm -rf /var/lib/apt/lists/*
RUN git clone --recursive https://github.com/c3rb3ru5d3d53c/binlex.git /src
WORKDIR /src
RUN cargo build --release --workspace

FROM debian:bullseye-slim
COPY --from=builder /src/target/release/binlex /usr/local/bin/binlex
# Keep container running infinitely
CMD ["tail", "-f", "/dev/null"]
