import json
import logging
import os

from lib.cuckoo.common.abstracts import Processing
from lib.cuckoo.common.path_utils import path_exists

log = logging.getLogger(__name__)


class JSLogProcessing(Processing):
    """Parse JSONL logs generated by the Bun interceptor."""

    order = 2

    def run(self):
        self.key = "js_log"

        log_name = self.options.get("log_name", "js_console.log")
        max_entries = int(self.options.get("max_entries", 10000))
        log_path = os.path.join(self.aux_path, log_name)

        output = {
            "path": log_path,
            "exists": False,
            "total_lines": 0,
            "parsed_lines": 0,
            "malformed_lines": 0,
            "truncated": False,
            "events": [],
            "http_requests": [],
            "http_responses": [],
            "http_errors": [],
            "console": [],
            "warnings": [],
            "init": [],
        }

        if not path_exists(log_path):
            return output

        output["exists"] = True

        try:
            with open(log_path, "r", encoding="utf-8", errors="replace") as f:
                for line in f:
                    output["total_lines"] += 1
                    text = line.strip()
                    if not text:
                        continue

                    if output["parsed_lines"] >= max_entries:
                        output["truncated"] = True
                        break

                    try:
                        event = json.loads(text)
                    except json.JSONDecodeError:
                        output["malformed_lines"] += 1
                        continue

                    output["parsed_lines"] += 1
                    output["events"].append(event)

                    event_type = event.get("event")
                    if event_type == "http_request":
                        output["http_requests"].append(event)
                    elif event_type == "http_response":
                        output["http_responses"].append(event)
                    elif event_type == "http_error":
                        output["http_errors"].append(event)
                    elif event_type == "console":
                        output["console"].append(event)
                    elif event_type == "warning":
                        output["warnings"].append(event)
                    elif event_type == "init":
                        output["init"].append(event)
        except Exception as e:
            log.warning("js_log_processing failed on %s: %s", log_path, e)

        return output
