import json
import logging
import os
from hashlib import sha256

from lib.cuckoo.common.abstracts import Processing
from lib.cuckoo.common.path_utils import path_exists, path_mkdir, path_read_file, path_write_file

log = logging.getLogger(__name__)


class JSLogProcessing(Processing):
    """Parse JSONL logs generated by the Bun interceptor."""

    order = 0

    @staticmethod
    def _bytes_from_buffer_dict(value):
        if not isinstance(value, dict):
            return None

        if value.get("type") != "Buffer":
            return None

        data = value.get("data")
        if not isinstance(data, list) or not data:
            return None

        try:
            if not all(isinstance(item, int) and 0 <= item <= 255 for item in data):
                return None
            return bytes(data)
        except Exception:
            return None

    def _extract_drop_candidates(self, node):
        candidates = []
        if isinstance(node, dict):
            if node.get("truncated") is False:
                for value in node.values():
                    payload = self._bytes_from_buffer_dict(value)
                    if payload:
                        candidates.append(payload)

            for value in node.values():
                candidates.extend(self._extract_drop_candidates(value))
        elif isinstance(node, list):
            for value in node:
                candidates.extend(self._extract_drop_candidates(value))
        return candidates

    def run(self):
        self.key = "js_log"

        log_name = self.options.get("log_name", "js_console.log")
        max_entries = int(self.options.get("max_entries", 10000))
        log_path = os.path.join(self.aux_path, "js_console", log_name)
        if not path_exists(log_path):
            log_path = os.path.join(self.aux_path, log_name)
        dropped_created = 0
        dropped_errors = 0
        dropped_paths = []
        seen_hashes = set()

        output = {
            "path": log_path,
            "exists": False,
            "log": "",
            "total_lines": 0,
            "parsed_lines": 0,
            "malformed_lines": 0,
            "truncated": False,
            "events": [],
            "http_requests": [],
            "http_responses": [],
            "http_errors": [],
            "console": [],
            "warnings": [],
            "init": [],
            "dropped_from_js_log": [],
            "dropped_created": 0,
            "dropped_errors": 0,
        }

        if not path_exists(log_path):
            return output

        output["exists"] = True

        try:
            output["log"] = path_read_file(log_path, mode="text")
            with open(log_path, "r", encoding="utf-8", errors="replace") as f:
                for line in f:
                    output["total_lines"] += 1
                    text = line.strip()
                    if not text:
                        continue

                    if output["parsed_lines"] >= max_entries:
                        output["truncated"] = True
                        break

                    try:
                        event = json.loads(text)
                    except json.JSONDecodeError:
                        output["malformed_lines"] += 1
                        continue

                    output["parsed_lines"] += 1
                    output["events"].append(event)

                    event_type = event.get("event")
                    if event_type == "http_request":
                        output["http_requests"].append(event)
                    elif event_type == "http_response":
                        output["http_responses"].append(event)
                    elif event_type == "http_error":
                        output["http_errors"].append(event)
                    elif event_type == "console":
                        output["console"].append(event)
                    elif event_type == "warning":
                        output["warnings"].append(event)
                    elif event_type == "init":
                        output["init"].append(event)

                    for payload in self._extract_drop_candidates(event):
                        digest = sha256(payload).hexdigest()
                        if digest in seen_hashes:
                            continue
                        seen_hashes.add(digest)

                        relative_path = os.path.join("files", digest)
                        abs_path = os.path.join(self.analysis_path, relative_path)

                        try:
                            if not path_exists(self.dropped_path):
                                path_mkdir(self.dropped_path, exist_ok=True)

                            if not path_exists(abs_path):
                                _ = path_write_file(abs_path, payload)

                            with open(self.files_metadata, "a", encoding="utf-8") as fh:
                                print(
                                    json.dumps(
                                        {
                                            "path": relative_path.replace("\\", "/"),
                                            "filepath": f"js_log/{event_type or 'event'}/{digest}",
                                            "pids": [],
                                            "ppids": [],
                                            "metadata": "",
                                            "category": "files",
                                        },
                                        ensure_ascii=False,
                                    ),
                                    file=fh,
                                )

                            dropped_created += 1
                            dropped_paths.append(relative_path.replace("\\", "/"))
                        except Exception as e:
                            dropped_errors += 1
                            log.warning("js_log_processing failed to drop extracted buffer for task %s: %s", self.task.get("id"), e)
        except Exception as e:
            log.warning("js_log_processing failed on %s: %s", log_path, e)

        output["dropped_from_js_log"] = dropped_paths
        output["dropped_created"] = dropped_created
        output["dropped_errors"] = dropped_errors
        return output
